- packages/networks/src/endpoints.ts
- update mainnet dmm endpoint from `https://dmm.exchange.injective.dev` to `https://dmm.exchange.injective.network`
> chore: update mainnet dmm endpoint

- packages/sdk-ts/src/client/exchange/types/derivatives.ts
- packages/sdk-ts/src/client/exchange/types/spot.ts
- packages/sdk-ui-ts/src/client/types/derivatives.ts
- packages/sdk-ui-ts/src/client/types/spot.ts
- packages/sdk-ui-ts/src/utils/derivatives.ts
- packages/sdk-ui-ts/src/utils/spot.ts
- updated `sdk-ui-ts` and `sdk-ts` packages with buy/sell limit order post-only order types.
- update changelog and package pump
- update `chain-api/injective/exchange/v1beta1/exchange_pb.d.ts` with `BUY_PO: 7` and `SELl_PO: 8` options for the `OrderTypeMap` enum which is used by `sdk-ts` `MsgCreateSpotLimitOrder.ts` `orderType` `Params`
> [WIP] chore: add postOnly to Msg Types

- deprecated/chain-consumer/src/transformers/ExchangeTransformer.ts
- deprecated/chain-consumer/src/types.ts
- packages/sdk-ts/src/client/chain/transformers/ChainGrpcExchangeTransformer.ts
- packages/sdk-ts/src/client/chain/types/exchange.ts
As per the response for [this endpoint](https://devnet-1.lcd.injective.dev/injective/exchange/v1beta1/fee_discount_account_info/inj1hkhdaj2a2clmq5jq6mspsggqs32vynpk228q3r) we need a volume property.
> chore: add volume property to FeeDiscountTierInfo interface

- packages/token-metadata/src/ibc/tokens.ts
- packages/token-metadata/src/tokens/tokens.ts
##Changes
- updated naming of 'USDT' token name to 'Tether'
- updated naming of 'USDC' token name to 'USD Coin'
- updated Axelar canonical IBC channel to `channel-84`
> chore: update token metadata

- packages/sdk-ts/src/core/exchange/msgs/MsgBatchCancelBinaryOptionsOrders.ts
- packages/sdk-ts/src/core/exchange/msgs/MsgBatchCancelDerivativeOrders.ts
- packages/sdk-ts/src/core/exchange/msgs/MsgBatchCancelSpotOrders.ts
- packages/sdk-ts/src/core/exchange/msgs/MsgCancelBinaryOptionsOrder.ts
- packages/sdk-ts/src/core/exchange/msgs/MsgCancelDerivativeOrder.ts
- packages/sdk-ts/src/core/exchange/msgs/MsgCancelSpotOrder.ts
This PR adds missing order mask to `MsgBatchCancelSpotOrder.ts`.
> fix: add order mask to batch cancel spot order message

- packages/sdk-ts/src/core/modules/bank/msgs/MsgSend.spec.ts
- packages/sdk-ts/src/core/modules/exchange/msgs/MsgBatchCancelBinaryOptionsOrders.spec.ts
- packages/sdk-ts/src/core/modules/exchange/msgs/MsgBatchCancelDerivativeOrders.spec.ts
- packages/sdk-ts/src/core/modules/exchange/msgs/MsgBatchCancelSpotOrders.spec.ts
- packages/sdk-ts/src/core/modules/exchange/msgs/MsgCancelBinaryOptionsOrder.spec.ts
- packages/sdk-ts/src/core/modules/exchange/msgs/MsgCancelDerivativeOrder.spec.ts
- packages/sdk-ts/src/core/modules/exchange/msgs/MsgCancelSpotOrder.spec.ts
- packages/sdk-ts/src/core/modules/gov/msgs/MsgDeposit.spec.ts
- packages/test-utils/src/mocks/index.ts
- adds unit test coverage on remaining EIP712 messages
- MsgBatchCancelBinaryOptionsOrders
- MsgBatchCancelDerivativeOrders
- MsgBatchCancelSpotOrders
- MsgCancelBinaryOptionsOrder
- MsgCancelDerivativeOrder
- MsgCancelSpotOrder
> feat: add unit test for remaining eip 712 messages

- packages/sdk-ts/package.json
- packages/sdk-ts/src/client/indexer/transformers/IndexerGrpcDerivativeTransformer.ts
- packages/sdk-ts/src/client/indexer/transformers/IndexerGrpcSpotTransformer.ts
- packages/sdk-ts/src/client/indexer/types/derivatives.ts
- packages/sdk-ts/src/client/indexer/types/spot.ts
- packages/ts-types/src/trade.ts
- yarn.lock
This PR makes the executionSide property visible on trade objects so we can use it to filter for either `maker` or `taker` side in our products.
> fix: added executionSide prop to trade objects

- packages/sdk-ui-ts/src/client/transformers/UiBridgeTransformer.ts
- packages/sdk-ui-ts/src/utils/bridge.ts
- add list of leap and Cosmosstation supported networks
- rename `convertKeplrToUiBridgeTransaction` to `convertCosmosWalletToUiBridgeTransaction` to be more inclusive of other cosmos wallets such as Leap. this method should get tested as part of QA as to whether this method will work for Leap as well
> chore: add lists of leap and cosmostation supported networks

- packages/sdk-ts/README.md
- pubkey type
`publicKey` in the example is already Base64.
- PrivateKey import path
fix PrivateKey import path.
- format
fix comment format.
- hex string type
it would be better to remove `'0x'` for those who use `privateKeyHash` with `'0x'`.
> fix: sdk-ts README.md

- packages/sdk-ui-ts/src/types/explorer.ts
- packages/sdk-ui-ts/src/types/index.ts
- packages/sdk-ui-ts/src/utils/explorer.ts
- packages/sdk-ui-ts/src/utils/index.ts
Utility method `getBlockExplorerPathFromNetworkType` can now be used across products to grab the appropriate block explorer url for a given address across Injective, Ethereum, and Cosmos block explorers. It can also easily be extended to other chains such as Solana.
> feat: utility methods for explorer

- packages/sdk-ts/src/client/indexer/transformers/IndexerRestExplorerTransformer.ts
- packages/sdk-ts/src/client/indexer/types/explorer-rest.ts
- packages/sdk-ts/src/client/indexer/types/explorer.ts
Add `errorLog` to the transformed response when querying for transaction details by tsx ID.
> chore: add optional errorLog to Transaction types

- packages/wallet-ts/src/strategies/wallet/strategies/WalletConnect.ts
Updates the type of request sent to Wallet Connect to allow for Metamask and many other wallets to properly sign transactions
> fix: fixes walletconnect signed tx type

- packages/sdk-ui-ts/src/token/TokenService.ts
- packages/sdk-ui-ts/src/types/token.ts
A helper method `getCW20AccountsBalanceWithToken` was added to the `TokenService` in support of explorer [PR](https://github.com/InjectiveLabs/injective-explorer/pull/207).
> chore: add helper method for getting cw account balance token metadata

- packages/sdk-ts/src/client/indexer/transformers/IndexerRestExplorerTransformer.ts
- packages/sdk-ts/src/client/indexer/types/explorer-rest.ts
- packages/sdk-ts/src/client/indexer/types/explorer.ts
Add proposal Id property to the `wasmCodeToExplorerWasmCode` transformer. The `proposal_id` property is already being returned via the indexer rest explorer api. Now, we will expose it to the UI via the transformer.  This will allow us to get the governance proposal id associated with a wasm code, for us to show on the explorer's code details page and will link to the appropriate governance proposal on the hub.
> chore: add proposal id to wasmCodeToExplorerWasmCode transformer

- packages/sdk-ts/src/core/modules/wasm/msgs/MsgStoreCode.ts
Issue: 
- sender is required by the chain 
- it was not being set in the MsgStoreCode but it was required by it.
> Set sender in store code

- packages/sdk-ts/src/core/utils/Denom/DenomClient.ts
- packages/token-metadata/src/tokens/network/devnet.ts
- packages/utils/src/helpers.ts
- resolves token metadata not populating on devnet issue
- resolves `ibcApi.fetchDenomTrace(hash)` onError halts `awaitForAll` utils function
> fix: token meta not populated on devnet env

- packages/sdk-ts/package.json
- packages/sdk-ts/src/client/indexer/grpc_stream/IndexerGrpcOracleStream.ts
- packages/sdk-ts/src/client/indexer/transformers/IndexerOracleStreamTransformer.ts
- yarn.lock
- add supports for the latest indexer grpc oracle stream for prices by marketIds
> feat: implement grpc oracle stream for prices by markets

- packages/sdk-ui-ts/src/client/transformers/UiBridgeTransformer.ts
- packages/sdk-ui-ts/src/types/bridge.ts
- packages/sdk-ui-ts/src/utils/bridge.ts
- packages/sdk-ui-ts/src/utils/explorer.ts
This PR makes it possible to get explorer link URL's attached to wormhole ethereum deposits.
> chore: add explorer link based on tsx for eth wh transfer

- packages/bridge-ts/src/wormhole/clients/SolanaWormholeClient.ts
- packages/sdk-ui-ts/src/types/bridge.ts
- packages/sdk-ui-ts/src/utils/bridge.ts
- the new `getTxResponse` for the `SolanaWormholeClient` will fetch a `TransactionResponse` based on a passed in `txHash.
- `RequestingVAA`  was added to the `BridgeTransactionState` in order to mark a transaction on the hub's bridge as being in a state of about to request a VAA. Therefore, if the user refreshes the page, they can see their order in the order details table, and the flow will go back to the point of trying to request a VAA from the WH guardians so that their transfer can be redeemed on the appropriate network end.
> chore: helper method for Solana getTxResponse

- packages/token-metadata/src/tokens/tokens/tokens.ts
Updates the puggo logo image suffix from .jpeg to .jpg to match the correct suffix of the puggo.jpg file.
> fix: puggo image suffix from jpeg to jpg

- packages/sdk-ts/src/core/modules/tx/api/TxGrpcApi.ts
FetchTxPoll throws an error if transaction has not been included in a block for a given timeout
This PR handles that error in Broadcast method.
> Handle unhanded error in TxGrpcAPI

- packages/sdk-ts/src/core/modules/authz/msgs/MsgGrant.spec.ts
- packages/sdk-ts/src/core/modules/authz/msgs/MsgGrant.ts
- packages/sdk-ts/src/core/modules/tx/eip712/maps.ts
- packages/sdk-ts/src/core/modules/tx/eip712/utils.ts
Hello,
These changes have been made to fix the MsgGrant message
https://github.com/InjectiveLabs/injective-ts/blob/master/packages/sdk-ts/src/core/modules/authz/msgs/MsgGrant.ts
I'm not sure about this change. Maybe this condition has been added for different messages. Do you know?
```
-   if (property === '@type' || property === 'type') {
+    if (property === '@type') {
```
Also, I have fixed feepayer for transaction of type eip 712
> Fix eip712 for date type and feePayer

- packages/sdk-ts/src/core/modules/tx/types/tx.ts
- packages/sdk-ts/src/core/modules/tx/utils/tx.ts
Each chain can have several different key types.  For some case,  I use '/cosmos.crypto.secp256k1.PubKey' for Injective chain
I'm also considering making a new pubKeyType field - pass the Proto Any object directly to the pubKey field. What do you think about it?
> Add signer pubkey type

- packages/exceptions/src/types/modules.ts
- packages/wallet-ts/src/strategies/types/strategy.ts
- packages/wallet-ts/src/strategies/wallet-strategy/WalletStrategy.ts
- packages/wallet-ts/src/strategies/wallet-strategy/strategies/Cosmostation.ts
- packages/wallet-ts/src/strategies/wallet-strategy/strategies/Keplr.ts
- packages/wallet-ts/src/strategies/wallet-strategy/strategies/Leap.ts
- packages/wallet-ts/src/strategies/wallet-strategy/strategies/Ledger/Base.ts
- packages/wallet-ts/src/strategies/wallet-strategy/strategies/Metamask.ts
- packages/wallet-ts/src/strategies/wallet-strategy/strategies/Torus.ts
- packages/wallet-ts/src/strategies/wallet-strategy/strategies/Trezor/index.ts
This pull request introduces a new feature to the Injective TS SDK, enabling the signing of arbitrary messages. The addition of this method expands the functionality of the wallet strategy.
**Key Changes:**
New Method: **signArbitrary** - This pull request adds a new method to the Injective TS SDK. This method enables the signing of arbitrary messages using crypto wallets.
> Add Method for Signing Arbitrary Messages

- packages/sdk-ts/package.json
- packages/sdk-ts/src/client/indexer/grpc/IndexerGrpcSpotApi.spec.ts
- packages/sdk-ts/src/client/indexer/grpc/IndexerGrpcSpotApi.ts
- packages/sdk-ts/src/client/indexer/transformers/IndexerGrpcSpotTransformer.ts
- packages/sdk-ts/src/client/indexer/types/spot.ts
- packages/sdk-ts/src/types/pagination.ts
- yarn.lock
- added `fetchAtomicSwapHistory` method to `IndexerGrpcSpotApi`
> chore: fetchAtomicSwapHistory added to sdk-ts

- packages/wallet-ts/src/strategies/wallet-strategy/strategies/Ledger/Base.ts
- ledger's `signPersonalMessage` param should be in hex format but not be `0x` prefixed. current implementation results in an error upon signing
> fix: ledger sign arbitrary

- .gitbook/core-modules/auction.md
- .gitbook/core-modules/authz.md
- .gitbook/core-modules/bank.md
- .gitbook/core-modules/distribution.md
- .gitbook/core-modules/exchange.md
- .gitbook/core-modules/governance.md
- .gitbook/core-modules/ibc.md
- .gitbook/core-modules/insurance.md
- .gitbook/core-modules/peggy.md
- .gitbook/core-modules/staking.md
- .gitbook/core-modules/token-factory.md
- .gitbook/core-modules/tokenfactory.md
- .gitbook/core-modules/wasm.md
- .gitbook/transactions/private-key.md
- packages/sdk-ts/src/core/modules/tx/broadcaster/MsgBroadcasterWithPk.spec.ts
- examples were added for `MsgExternalTransfer` itself and also specifically for adding coins to the burn auction pool per [notion](https://www.notion.so/injective/Frontend-Team-Dashboard-cfa9a0cacd1c40afb5ab399d68bae83c?p=64a9cd97c3af4c2cb291ea756d24be45&pm=s).
- in addition, I noticed that some of the parameters passed to `MsgBroadcasterWithPk` in our examples are now deprecated, so I fixed that across the docs
> chore: msgExternalTransfer examples

- .gitbook/calulations/README.md
- .gitbook/calulations/minPriceTickSize.md
- .gitbook/calulations/minQuantityTickSize.md
- adds docs for calculating market min price tick size
- adds docs for calculating market min quantity tick size
> chore: docs for calculating market price quantity tick size

- packages/sdk-ts/src/client/wasm/nameservice/utils.ts
- packages/sdk-ui-ts/package.json
- packages/sdk-ui-ts/src/denom/DenomClientAsync.ts
- packages/sdk-ui-ts/src/services/ibc/ibcTokenMetadata.json
- packages/sdk-ui-ts/src/services/ibc/tokens.ts
- new service to fetch ibc token metadata was added
- script to fetch updated ibc denom metadata will run at the end of `yarn build` in `sdk-ui-ts`
- fetching and transforming of the token metadata retrieved from api is kept within `src/services/ibc/tokens` as to handle  both the fetching and mapping at build time
- various conditional checks were added to ensure  `ibcTokenMetadata.json` will exist when it's being referenced by `DenomClientAsync.ts` in the header ->`import ibcTokenMetadata from '../services/ibc/ibcTokenMetadata.json
`
- from `DenomClientAsync.ts` perspective the flow is the following:
1. denom traces related to the ibc token will be fetched
2. the denom will be checked as to whether it exists in the hardcoded `tokens.ts` list. and if not, the metadata will be retried from …
> chore: ibc tokens script

- .github/workflows/canary.yml
- .github/workflows/dev.yaml
- .github/workflows/stable.yaml
- packages/sdk-ui-ts/package.json
-- yaml build scripts will now check if there was any updates to `ibcTokenMetadata.json` during the build. if so, it will push a new commit to handle the update, which should propogate along with the publish step
1. checks if there is any new diff between the previous `ibcTokenMetadata.json` and the potentially updated one from the build
2. if there is a diff, the `git add`/ `git commit` logic will execute
3. if there is no diff, then the `git diff --exit-code` command will return `0`, so the `git add`/`git commit` steps will not execute
Note: took some time to come up with this but seems to work nicely
- forked `injective-ts` -> updated package names to where they would publish to `@shane-moore/...` instead of to `@injectivelabs/`. then, I updated the `ibcTokenMetadata.json` to test the …
> chore: update yml files for ibc tokens script

- packages/token-metadata/src/tokens/mappings/mapBySymbol.ts
- it's possible for a `tokenMeta` object in `tokens.ts` to have multiple properties i.e. `ibc`/`spl`/`cw20s` in any combination, and each of these sub properties could be used to create a new `denom/`tokenMeta` pair in the `TokenMetaUtils` `this.tokens`. therefore, we need to extend `mapBySymbol` to return results for the various token types instead of returning early if it hits `if (tokenMeta.ibc && tokenMeta.ibc.baseDenom) ` for example, because there may also be a `cw20s` property associated with it, which is the case for `USDC`, which has `ibc` and `cw20s` tokens that need to be created
- hub bridge now shows USDCet. it's currently being omitted in latest published packages, since `mapBySymbol` is only returning the `ibc` property's token meta. I tested with this change, and USDCet …
> chore: mapBySymbol support multiple token types

- packages/sdk-ui-ts/src/types/bridge.ts
- packages/sdk-ui-ts/src/utils/bridge.ts
- packages/token-metadata/src/ibc/channels.ts
- packages/token-metadata/src/tokens/tokens/tokens.ts
- packages/ts-types/src/cosmos.ts
- packages/wallet-ts/src/utils/wallets/cosmos/endpoints.ts
- Celestia bridge was added using details noted in [slack convo](https://injectivelabsinc.slack.com/archives/C03A9FKG878/p1698701353757959)
- note that potential changes are possible, pending our first ibc transfer. any changes will be noted in the slack channel. 
- the packages in this PR should be `yarn link`ed to hub in order to test the bridge out, after the first IBC transfer to Injective. This is because we need the denom to exist in the bank module for hub bridge to recognize the new denom
> chore: celestia bridge

- packages/wallet-ts/src/strategies/cosmos-wallet-strategy/strategies/Cosmostation.ts
- packages/wallet-ts/src/utils/wallets/cosmostation/CosmostationWallet.ts
- added `checkChainIdSupport` check to cosmostation `getAddresses`, similar to `keplr` and `leap`
- tried `Migaloo` network with cosmostation and got error message as expected:
> chore: add supported chainId check to cosmostation getAddresses

- .gitbook/core-modules/staking.md
- packages/sdk-ts/src/core/modules/msgs.ts
- packages/sdk-ts/src/core/modules/staking/index.ts
- packages/sdk-ts/src/core/modules/staking/msgs/MsgCancelUnbondingDelegation.spec.ts
- packages/sdk-ts/src/core/modules/staking/msgs/MsgCancelUnbondingDelegation.ts
- packages/sdk-ts/src/core/modules/tx/eip712/maps.ts
- packages/ts-types/src/enums.ts
- `MsgCancelUnbondingDelegation` allows you to cancel any amount you are currently unbonding. Then, it will reset the bonding period and redelegate to the same validator. This PR adds support for this message
- unit tests & git book examples were also created
- small addition to eip712 mappings for `creation_height` property to convert type to `int64`
> chore: msgCancelUnbondingDelegation created

- .gitbook/building-dapps/configuring-nuxt.md
- updated the `building-dapps` docs to reference latest nuxt version and similar latest packages
- updated `vite` config to import `vite-tsconfig-paths` as to help prevent the developer from having to search for a resource on how to get his TS file absolute paths to work
- removed `pinia` dependency since we get that as a sub-dependency from `@pinia/nuxt`
> chore: building-dapps docs update

- packages/sdk-ui-ts/src/constants.ts
- packages/sdk-ui-ts/src/services/gas/estimator.ts
- packages/sdk-ui-ts/src/services/web3/Web3Composer.ts
- a testnet `TIP` of 1.5 was added for peggy tsx `maxPriorityFeePerGas`, which is the max amount of gas fee a user would be wiling to pay (on top of the default gas that is burned from each tsx). we were previously using a `TIP` of 2, just like for mainnet. Then, we use alchemy to get back an estimated `maxFeePerGas`, which is much lower. This was causing the error shown in this screenshot:
In this PR, we lower the `maxPriorityFeePerGas` to 1.5 `GWEI` for testnet tsx so that it will be lower than the alchemy estimated `maxFeePerGas`
In addition, this PR fixes the following issue:  the`fetchGasPrice` method below's first try/catch block's `fetchEstimatorGasPrice` will fail everytime because `fetchEstimatorGasPrice`'s nested method `formatFeeHistory` has the following issues:  
- …
> chore: peggy gas for testnet

- packages/sdk-ui-ts/src/utils/bridge.ts
- packages/token-metadata/src/tokens/mappings/mapByHash.ts
- packages/token-metadata/src/tokens/mappings/mapBySymbol.ts
- packages/token-metadata/src/tokens/tokens/index.ts
- packages/token-metadata/src/tokens/tokens/testnet-tokens.ts
- packages/token-metadata/src/tokens/tokens/tokens.ts
- packages/token-metadata/src/types.ts
- packages/token-metadata/src/utils/helpers.ts
- packages/token-metadata/src/utils/meta.ts
- packages/token-metadata/src/utils/token.ts
- tokens coming from networks such as `Ethereum`/`Solana`/ etc via WH will now be minted on Injective as `ibc` bank denoms, i.e. `ibc/<ibcHash>`
- therefore, the `token-metadata` package will need to support multiple `ibc` metadata's per symbol `key` in the `tokens.ts` file. This PR is an initiative to accomplish this
-  refactoring `.ibc` properties on token meta in `tokens.ts` to be `.ibcs`, each with a different `source`.  If they come from a cosmos chain, it'd be `source: TokenSource.Cosmos`, for example. The implementation is similar to how we abstracted `cw20` to  `cw20s`, so now there can be multiple ibc subdenoms from different sources.
- we use getTokenInfo to grab the correct ibc object from a token's `.ibcs` array, using the `TokenSource`, and the products will be returned a …
> chore: add ibcs property to tokens

- packages/sdk-ui-ts/src/denom/DenomClientAsync.ts
- packages/sdk-ui-ts/src/token/TokenService.ts
- packages/token-metadata/src/tokens/tokens/tokens.ts
- For perp markets, we don't have a `denom` for the base symbol. We just know the `base symbol`, and we're trying to derive the token metadata from `token-metadata` package using `DenomClient.getDenomToken` in the same way that we would if we were trying to derive the metadata via passing the denom. This leads to edge cases and complexity
- In this PR, I propose that simply the flow by grabbing token metadata for derivatives markets "base tokens" via `DenomClient.getTokenMetaDataBySymbol` and then adding a few required fields to return a proper `Token` type. Note that it seems like the only useful fields for a derivative base token is the `name` / `symbol` / `logo` properties. The rest don't seem to be used, which is why I feel like the simplification I'm making here with the new …
> chore: perp markets token metadata
