InjectiveLabs/injective-ts

- packages/exchange-consumer/src/consumers/BridgeTransactionConsumer.ts
- updates bridge transaction consumer
> chore: update bridge transaction consumer

- packages/exchange-consumer/src/transformers/AuctionTransformer.ts
- packages/referral-consumer/.npmignore
- packages/referral-consumer/README.md
- packages/referral-consumer/jest.config.js
- packages/referral-consumer/package.json
- packages/referral-consumer/src/BaseConsumer.ts
- packages/referral-consumer/src/consumers/ReferralConsumer.ts
- packages/referral-consumer/src/consumers/index.ts
- packages/referral-consumer/src/index.ts
- packages/referral-consumer/src/transformers/ReferralTransformer.ts
- packages/referral-consumer/src/transformers/index.ts
- packages/referral-consumer/src/types/index.ts
- packages/referral-consumer/tsconfig.build.json
- packages/referral-consumer/tsconfig.json
- yarn.lock
- implements the referral consumer package
> feat: implement referral consumer

- packages/contracts/package.json
- packages/contracts/src/addresses.ts
- packages/contracts/src/types.ts
- packages/ui-common/src/peggy/action.ts
- packages/ui-common/src/peggy/index.ts
- packages/ui-common/src/peggy/transformer.ts
- packages/ui-common/src/peggy/utils.ts
- packages/ui-common/src/token/erc20Service.ts
- packages/ui-common/src/token/erc20ServiceAction.ts
- adds support to set devnet peggy and injective contract address
> feat: add support for devnet peggy and injective contract address

- packages/sdk-ts/src/client/chain/grpc/ChainGrpcWasmApi.ts
- packages/sdk-ts/src/client/chain/transformers/ChainGrpcWasmTransformer.ts
- packages/sdk-ts/src/client/chain/types/wasm.ts
- add functionality to query on chain cosmswasm contract info
> feat: add functionality to query on chain cosmswasm contract info

- packages/sdk-ts/src/client/exchange/rest/ExchangeRestExplorerApi.ts
- packages/sdk-ui-ts/src/utils/helpers.ts
This PR addresses the concerns noted [here](https://github.com/InjectiveLabs/injective-explorer/pull/99#discussion_r931894220) and [here](https://github.com/InjectiveLabs/injective-hub/pull/661#discussion_r932157698).
> chore: create getTokenLogoFromTokenType helper method and add error handling for fetchCW20Balances

- packages/sdk-ts/src/core/authz/index.ts
- packages/sdk-ts/src/core/authz/msgs/MsgExec.ts
- packages/sdk-ts/src/core/authz/msgs/MsgGrant.ts
- packages/sdk-ts/src/core/msgs.ts
Hello,
I added a new message type (MsgExec) to authz module and add a new param expiryInSeconds for MsgGrant
Also, I think we need to delete param expiryInYears. What do you think about it?
> WIP:  Auths module - add MsgExec and new param MsgGrant

- packages/sdk-ts/package.json
- packages/sdk-ts/src/client/indexer/grpc/IndexerGrpcDerivativesApi.ts
- packages/sdk-ts/src/client/indexer/grpc/IndexerGrpcSpotApi.ts
- packages/sdk-ts/src/client/indexer/transformers/IndexerGrpcDerivativeTransformer.ts
- packages/sdk-ts/src/client/indexer/transformers/IndexerGrpcSpotTransformer.ts
- packages/sdk-ts/src/client/indexer/types/derivatives.ts
- packages/sdk-ts/src/client/indexer/types/spot.ts
- packages/sdk-ui-ts/src/client/types/derivatives.ts
- packages/sdk-ui-ts/src/client/types/spot.ts
- yarn.lock
This PR implements latest indexer changes which adds support for order history.
> feat: order history

- packages/token-metadata/src/tokens/tokens.ts
- update terra USD decimals from 6 to 18
> fix: token decimals for terra from 6 to 18

- packages/sdk-ts/README.md
- fix examples using TxGrpcClient
> fix: sdk-ts README.md

- packages/sdk-ts/src/core/modules/authz/msgs/MsgGrant.ts
This MR close: #101
Fix: MsgGrant for DirectSign
- Add new property Expiration
> Fix MsgGrant for DirectSign

- packages/bridge-ts/src/wormhole/constants.ts
- packages/contracts/src/addresses.ts
- packages/networks/src/endpoints.ts
- packages/networks/src/network.ts
- packages/networks/src/old-endpoints.ts
- packages/networks/src/types.ts
- packages/sdk-ts/src/utils/constants.ts
- packages/sdk-ui-ts/src/constants.ts
- packages/sdk-ui-ts/src/services/gas/index.ts
- packages/sdk-ui-ts/src/utils/bridge.ts
- packages/token-metadata/src/TokenMetaUtilFactory.ts
- packages/token-metadata/src/tokens/helpers/testnetMap.ts
- packages/token-metadata/src/tokens/maps/bySymbolForTestnet.ts
- packages/token-metadata/src/tokens/maps/index.ts
> chore: add devnet 2 config

- packages/sdk-ts/src/core/modules/wasm/index.ts
- packages/sdk-ts/src/core/modules/wasm/msgs/MsgMigrateContract.ts
> Add msg migrate contract

- packages/exceptions/src/exceptions/TransactionException.ts
- packages/exceptions/src/exceptions/Web3GatewayTransactionException.ts
- packages/exceptions/src/exceptions/index.ts
- packages/exceptions/src/messages.ts
- packages/exceptions/src/types/codes.ts
- packages/exceptions/src/utils/maps.ts
- packages/sdk-ts/src/client/indexer/grpc/IndexerGrpcTransactionApi.ts
- packages/sdk-ts/src/core/modules/tx/api/TxGrpcApi.ts
- packages/sdk-ts/src/core/modules/tx/api/TxRestApi.ts
- packages/wallet-ts/src/broadcaster/MsgBroadcaster.ts
- packages/wallet-ts/src/strategies/cosmos/strategies/Cosmostation.ts
- packages/wallet-ts/src/strategies/cosmos/strategies/Keplr.ts
- packages/wallet-ts/src/strategies/cosmos/strategies/Leap.ts
- packages/wallet-ts/src/strategies/wallet/strategies/Cosmostation.ts
- packages/wallet-ts/src/strategies/wallet/strategies/Keplr.ts
- packages/wallet-ts/src/strategies/wallet/strategies/Leap.ts
- packages/wallet-ts/src/utils/wallets/keplr/KeplrWallet.ts
Currently, error codes are duplicated between modules, resulting in UI showing the wrong error toast. This PR maps chain error exceptions by the module type, ensuring that the toast content is accurate to the chain error.
> feat: map chain error exception by module

- packages/token-metadata/src/utils.ts
This PR attempts to resolve the scenario mentioned in https://www.notion.so/injective/91856a6f88874b03b9098f6980e0414f?v=6d230a442a594f05af3667d8f32a5759&p=a51e702fce70471ba566ba90854f2aba&pm=s.
> fix: factory token decimals

- packages/token-metadata/src/TokenInfo.ts
- packages/token-metadata/src/TokenMetaUtils.ts
- packages/token-metadata/src/tokens/mappings/mapByAddress.ts
- packages/token-metadata/src/tokens/mappings/mapByHash.ts
- packages/token-metadata/src/tokens/mappings/mapBySymbol.ts
- packages/token-metadata/src/tokens/network/testnet.ts
- packages/token-metadata/src/tokens/tokens/cw20-tokens.ts
- packages/token-metadata/src/tokens/tokens/index.ts
- packages/token-metadata/src/tokens/tokens/tokens.ts
- packages/token-metadata/src/types.ts
- packages/token-metadata/src/utils.ts
- packages/token-metadata/test/unit/cw20.spec.ts
> refactor: token metadata typing

- packages/token-metadata/src/utils.ts
This PR Adds a `getUntrackedToken` helper function.
> chore: get untracked token

- packages/sdk-ts/package.json
- packages/sdk-ts/src/client/chain/grpc/ChainGrpcGovApi.spec.ts
- packages/sdk-ts/src/client/chain/grpc/ChainGrpcGovApi.ts
- packages/sdk-ts/src/client/chain/grpc/ChainGrpcMintApi.ts
- packages/sdk-ts/src/client/chain/transformers/ChainGrpcGovTransformer.ts
- packages/sdk-ts/src/client/chain/types/gov.ts
- packages/sdk-ts/src/core/modules/gov/ProposalContentDecomposer.ts
- packages/sdk-ts/src/core/modules/gov/msgs/MsgDeposit.ts
- packages/sdk-ts/src/core/modules/gov/msgs/MsgSubmitProposalExpiryFuturesMarketLaunch.ts
- packages/sdk-ts/src/core/modules/gov/msgs/MsgSubmitProposalPerpetualMarketLaunch.ts
- packages/sdk-ts/src/core/modules/gov/msgs/MsgSubmitProposalSpotMarketLaunch.ts
- packages/sdk-ts/src/core/modules/gov/msgs/MsgSubmitProposalSpotMarketParamUpdate.ts
- packages/sdk-ts/src/core/modules/gov/msgs/MsgSubmitTextProposal.ts
- packages/sdk-ts/src/core/modules/gov/msgs/MsgVote.ts
- yarn.lock
> feat: gov update for 0.47

- packages/sdk-ts/src/client/indexer/rest/IndexerRestExplorerApi.ts
> feat: sc search

- packages/sdk-ts/src/client/indexer/rest/IndexerRestExplorerApi.ts
- packages/sdk-ts/src/client/indexer/transformers/IndexerRestExplorerTransformer.ts
- packages/sdk-ts/src/client/indexer/types/explorer-rest.ts
- packages/sdk-ts/src/client/indexer/types/explorer.ts
- Added fetchCommunitySpendPool transactions
> feat: community spend pool

- packages/sdk-ui-ts/src/utils/mappings.ts
I sent a previous PR: https://github.com/InjectiveLabs/injective-ts/pull/228 but the filename was not correct.
This PR fix the image name for our validator.
> fix: wrong image name

- packages/sdk-ts/package.json
- packages/sdk-ts/src/client/indexer/grpc/IndexerGrpcCampaignApi.ts
- yarn.lock
> feat: rounds api

- packages/sdk-ts/package.json
- packages/sdk-ts/src/client/chain/grpc/ChainGrpcIbcApi.spec.ts
- packages/sdk-ts/src/client/chain/grpc/ChainGrpcIbcApi.ts
- packages/sdk-ts/src/core/modules/ibc/msgs/MsgTransfer.ts
- yarn.lock
[jira](https://injective-labs.atlassian.net/browse/ECO-270)
[investigation](https://www.notion.so/injective/MsgTransfer-V0-50-Inquiry-14294643a7e44649814fa8f8ccf8d424?showMoveTo=true&saveParent=true)
updated `core-proto-ts` per [slack](https://injectivelabsinc.slack.com/archives/C04BR23F2U9/p1722279493234479?thread_ts=1722217915.937459&cid=C04BR23F2U9)
Testing completed:
- deposit/withdraw via `MsgTransfer`
- ran unit test and passed `yarn jest ./packages/sdk-ts/src/client/chain/grpc/ChainGrpcIbcApi.spec.ts`
> fix: msgTransfer tokens param

- packages/sdk-ts/package.json
- packages/sdk-ts/src/client/olp/grpc/OLPGrpcApi.spec.ts
- packages/sdk-ts/src/client/olp/grpc/OLPGrpcApi.ts
- packages/sdk-ts/src/client/olp/grpc/transformers/index.ts
- packages/sdk-ts/src/client/olp/grpc/types/index.ts
- yarn.lock
jira task = https://injective-labs.atlassian.net/browse/IL-96
> chore: update for olp mini epoch per proto changes
